### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by manderio** [manderio/mandotlin#1]
To-Do List for the bot, will store issues with features added here as they are being worked on to create separate to-dos. To add to this, create a comment with a feature list of a relevant issue. If I see something that is irrelevant/useless, I will remove it. For feature requests, do not post them here, instead do a feature request. 

Thank you!

**Comment by elkowar** [comment]
todo: #2

**Comment by manderio** [comment]
Initial setup:
- [ ] Test server
- [ ] Test bot
- [ ] Dependency list
- [ ] Google sheets integration library
- [ ] General project structure

Fluff:
- [ ] Icon stuff
- [ ] readme.md niceness
- [ ] Complete feature list
